site_name: AI Student Cloud Documentation
nav:
  - Overview:
    - Quick Overview of AI Student Cloud: index.md
    #- What can I use the AI Student Cloud for?: overview/subpage-1.md
    #- Subpage 2: overview/subpage-2.md

  - Getting Started:
    - Getting Access: getting-started/getting-access.md
    - File Transfer: getting-started/file-transfer.md
    - Running Jobs: getting-started/running-jobs.md


  - Application Guides:
    - "Interactive TensorFlow": application-guides/interactive-tensorflow.md
    - "PyTorch and Anaconda": application-guides/pytorch-anaconda.md
    - "Matlab": application-guides/matlab.md
    - "Multi-GPU data parallelism training with Horovod and Keras": application-guides/multi-gpu-keras.md
    - "PyTorch and automatic mixed precision with APEX": application-guides/torch-amp.md
    - "Python pip in containers": application-guides/pip-in-containers.md
    - "Mount user directory on your local computer": application-guides/mount-dir.md

  - Help:
    - Getting Help: help/getting-help.md
    - FAQ: help/faq.md

theme:
  name: material
  #custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - toc.integrate
    - navigation.indexes
    - navigation.sections
    - content.tabs.link
    - navigation.footer
    - content.code.copy

  logo: assets/logo_round.png
  favicon: assets/favicon.ico

  font:
    text: barlow
 
  language: en

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/aau-claaudia/aicloud-docs

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc
#  - pymdownx.keys
#  - pymdownx.highlight:
#      linenums: true
#      linenums_style: pymdownx-inline

#  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/claaudia/
      name: Claaudia on LinkedIn

    - icon: fontawesome/solid/globe
      link: https://www.researcher.aau.dk/contact/claaudia

  #generator: True

copyright: Copyright &copy; 2024 CLAAUDIA


#extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
#  - javascripts/config.js
#extra_css:
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
