# Project information
site_name: AI-LAB Documentation
site_url: #TODO: update
site_author: CLAAUDIA, ITS, Aalborg University
site_description: >-
  Documentation for AI-LAB, a powerful computing platform available to students at Aalborg University, designed to support intensive computational tasks, particularly those involving machine learning.

# Repository
repo_name: aau-claaudia/ai-student-cloud-docs  #TODO: update 
repo_url: #TODO: update

# Copyright
copyright: Copyright &copy; 2024 CLAAUDIA

nav:
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">home</span>Home</span>: index.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">settings</span>System overview</span>: system-overview.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">developer_guide</span>Guidelines</span>: guidelines.md
  - <span class='custom-nav-item hr'><span class="material-symbols-outlined nav-icon">rocket_launch</span>Getting started</span>:
    - "Preperation": getting-started/preperation.md
    - "Login": getting-started/login.md
    - "File transfer": getting-started/file-transfer.md
    - "Getting applications": getting-started/getting-applications.md
    - "Running applications": getting-started/running-applications.md
    - "Offboarding": getting-started/offboarding.md
  - <span class='custom-nav-item hr'><span class="material-symbols-outlined nav-icon">code_blocks</span>Useful commands</span>:
    - "Terminal basics": additional-guides/terminal-basics.md
    - "Checking the queue": additional-guides/checking-the-queue.md
    - "Checking the status of compute nodes": additional-guides/checking-the-status-of-compute-nodes.md
    - "Running a container in interactive mode": "additional-guides/running-a-container-in-interactive-mode.md"
    - "Setting a time limit": additional-guides/setting-a-time-limit.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">package_2</span>Getting container images</span>:
    - "Building your own container image": additional-guides/building-your-own-container-image.md
    - "Download images from NGC": additional-guides/download-images-from-ngc.md
    - "Creating a conda environment": additional-guides/creating-a-conda-environment.md
    - "Download memory consuming images":  additional-guides/download-memory-consuming-images.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">note_stack</span>Application guides</span>:
    - "MATLAB":  additional-guides/application-guides/matlab.md
    - "ImageMagick":  additional-guides/application-guides/imagemagick.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">school</span>Courses</span>:
    - "Customize containers": courses/customize-containers.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">edit_note</span>For lecturers</span>:
    - "Adding a course": additional-guides/for-lecturers/adding-a-course.md
    - "Page design guide": additional-guides/for-lecturers/page-design-guide.md

  - <span class='custom-nav-item hr'><span class="material-symbols-outlined nav-icon">quiz</span>FAQ</span>: faq.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">dictionary</span>Glossery</span>: glossery.md
  - <span class='custom-nav-item'><span class="material-symbols-outlined nav-icon">help</span>Support</span>: support.md


    
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.code.annotate

  logo: assets/logo_round.png
  favicon: assets/favicon.ico

  font:
    text: barlow
 
  language: en

  icon:
    annotation: material/plus-circle

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/claaudia/
      name: Claaudia on LinkedIn

    - icon: fontawesome/solid/globe
      link: https://www.researcher.aau.dk/contact/claaudia
