# Project information
site_name: AI Student Cloud Documentation
site_url: #TODO: update
site_author: CLAAUDIA, ITS, Aalborg University
site_description: >-
  Documentation for AI Student Cloud, a powerful computing platform available to students at Aalborg University, designed to support intensive computational tasks, particularly those involving machine learning.

# Repository
repo_name: aau-claaudia/ai-student-cloud-docs  #TODO: update 
repo_url: #TODO: update

# Copyright
copyright: Copyright &copy; 2024 CLAAUDIA

nav:
  - Home:
    - Home: index.md
    - System Overview: system-overview.md
    - Guidelines: guidelines.md
    - FAQ: faq.md
    - Glossery: glossery.md
    - Support: support.md
      
  - Getting Started:
    - "1. Preperation": getting-started/preperation.md
    - "2. Login": getting-started/login.md
    - "3. File transfer": getting-started/file-transfer.md
    - "4. Getting applications": getting-started/getting-applications.md
    - "5. Running applications": getting-started/running-applications.md
    - "6. Offboarding": getting-started/offboarding.md

  - Additional Guides:
    - Useful Commands:
      - "Terminal basics": additional-guides/terminal-basics.md
      - "Checking the queue": additional-guides/checking-the-queue.md
      - "Checking the status of compute nodes": additional-guides/checking-the-status-of-compute-nodes.md
      - "Running a container in interactive mode": "additional-guides/running-a-container-in-interactive-mode.md"
      - "Setting a time limit": additional-guides/setting-a-time-limit.md
    - Creating containers:
      - "Download containers from NGC": additional-guides/download-containers-from-ngc.md
      - "Creating a conda environment": additional-guides/creating-a-conda-environment.md
      - "Download memory consuming containers":  additional-guides/download-memory-consuming-containers.md

  - Courses:
    - ""
      #- "Customize Containers": courses/customize-containers.md
      #- "Obtaining Memory Consuming Containers": courses/obtaining-memory-consuming-containers.md
      #- "Obtaining Containers Faster": courses/obtaining-containers-faster.md
      #- "Open a Shell in a Container": courses/open-a-shell-in-a-container.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.footer
    - content.code.copy
    - content.code.annotate

  logo: assets/logo_round.png
  favicon: assets/favicon.ico

  font:
    text: barlow
 
  language: en

  icon:
    annotation: material/plus-circle

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/claaudia/
      name: Claaudia on LinkedIn

    - icon: fontawesome/solid/globe
      link: https://www.researcher.aau.dk/contact/claaudia
