site_name: AI Student Cloud Documentation
nav:
  - Overview:
    - Overview of AI Student Cloud: index.md
    - System Overview: overview/system-overview.md
    - Fair Usage: overview/fair-usage.md
    - FAQ: overview/faq.md
    - Support: overview/support.md
    
  - Getting Started:
    - Getting Access: getting-started/getting-access.md
    - File Transfer: getting-started/file-transfer.md
    - Installing Applications: getting-started/installing-applications.md
    - Running Jobs: getting-started/running-jobs.md

  - Application Guides:
    - "Matlab": application-guides/matlab.md
    #- "Interactive TensorFlow": application-guides/interactive-tensorflow.md
    #- "PyTorch and Anaconda": application-guides/pytorch-anaconda.md
    #- "Multi-GPU data parallelism training with Horovod and Keras": application-guides/multi-gpu-keras.md
    #- "PyTorch and automatic mixed precision with APEX": application-guides/torch-amp.md
    #- "Python pip in containers": application-guides/pip-in-containers.md
    #- "Mount user directory on your local computer": application-guides/mount-dir.md
    #- "Jupyter": application-guides/jupyter.md

  - Additional Guides:
    - "Building Memory Consuming Containers": additional-guides/building-memory-consuming-containers.md
    - "Building Containers Faster": additional-guides/building-containers-faster.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - content.tabs.link
    - navigation.footer
    - content.code.copy
    - hide.navigation
    - content.code.annotate

  logo: assets/logo_round.png
  favicon: assets/favicon.ico

  font:
    text: barlow
 
  language: en

  icon:
    annotation: material/plus-circle


extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/aau-claaudia/aicloud-docs #TODO: change url

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - def_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/claaudia/
      name: Claaudia on LinkedIn

    - icon: fontawesome/solid/globe
      link: https://www.researcher.aau.dk/contact/claaudia

  #generator: True

copyright: Copyright &copy; 2024 CLAAUDIA


#extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
#  - javascripts/config.js
#extra_css:
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
