name: Deploy MkDocs

on:
  push:
    branches:
      - master  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install mkdocs mkdocs-material
    - run: mkdocs build --verbose --clean --strict
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        deploy_dir: ./site